### ISSUE TITLE
Configuration names can conflict with a plug-in's schema.

### ISSUE THREAD

**Issue by EndureBlaze** [hexojs/hexo-renderer-markdown-it#139]
Like this:
![image_11.png](https://i.loli.net/2020/11/19/T6rpSDGKLfXjhHk.png)

The name of the plug-in is [YAML-Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)

It seems that `markdown:` is recognized as the `Markdown Processor` for this plug-in model.

Is it possible to change `markdown:` to `markdown-it:` or something else?

**Comment by SukkaW** [comment]
Although `markdown` might be conflicted with some YAML processing plugin, but technically `markdown` is not a reserved keyword, thus it is not violating the [YAML spec](https://yaml.org/spec/).

Considering uninstall that plugin instead since it treat `markdown` as a reserved keyword, which is violating the YAML spec.

**Comment by EndureBlaze** [comment]
> 
> 
> Although `markdown` might be conflicted with some YAML processing plugin, but technically `markdown` is not a reserved keyword, thus it is not violating the [YAML spec](https://yaml.org/spec/).
> 
> Considering uninstall that plugin instead since it treat `markdown` as a reserved keyword, which is violating the YAML spec.

thx
